In [2]:
import os
import sys

# Go two levels up from the current working directory
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
parent_dir_2 = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(parent_dir)
sys.path.append(parent_dir_2)

In [3]:
import XFTK
import importlib

In [81]:
importlib.reload(XFTK)

In [82]:
WNM5 = XFTK.BondFuture(contract = 'USM5')

In [83]:
from tia.bbg import LocalTerminal

In [84]:
resp = LocalTerminal.get_historical('WNM5 Comdty', ['RK074', 'CONVENTIONAL_CTD_FORWARD_FRSK', 'PX_LAST'], start = '2025-03-28', end = '2025-03-28', ignore_field_error = 1)
fut_data = resp.as_frame()

In [85]:
WNM5.DLV(tradeDate = '2025-03-07', actualRepo = 4.280).sort_values(by = 'implied_repo', ascending = False)

,ticker,coupon,maturity,price,yield,gross_basis,implied_repo,actual_repo,BNOC
2,T,4.750,2041-02-15,102.17970,4.555868,0.105437,4.278676,4.28,0.000422
1,T,4.250,2040-11-15,96.59375,4.555821,0.153987,3.814996,4.28,0.140521
3,T,4.375,2041-05-15,97.75781,4.572082,0.256474,3.559633,4.28,0.220284
0,T,3.875,2040-08-15,92.62500,4.544765,0.268207,3.221124,4.28,0.305944
53,T,4.750,2043-11-15,101.28130,4.646142,0.676907,2.471499,4.28,0.572957
4,T,3.750,2041-08-15,90.39844,4.588013,0.503095,2.330392,4.28,0.549752
54,T,4.500,2044-02-15,97.93750,4.664974,0.681143,2.327094,4.28,0.596777
52,T,4.375,2043-08-15,96.61719,4.650012,0.655718,2.315043,4.28,0.592339
55,T,4.625,2044-05-15,99.44531,4.668595,0.707418,2.295613,4.28,0.617246
49,T,4.000,2042-11-15,92.39844,4.634068,0.613263,2.132588,4.28,0.620386
51,T,3.875,2043-05-15,90.46094,4.658110,0.658920,1.881078,4.28,0.678469
50,T,3.875,2043-02-15,90.69531,4.644991,0.671643,1.863547,4.28,0.683685
57,T,4.625,2044-11-15,99.32813,4.677111,0.846882,1.849346,4.28,0.755150
12,T,3.625,2043-08-15,87.06250,4.679980,0.655179,1.717256,4.28,0.695984
13,T,3.750,2043-11-15,88.48438,4.681053,0.712180,1.591755,4.28,0.743635
48,T,3.375,2042-08-15,84.92969,4.645375,0.633848,1.549122,4.28,0.723390
47,T,3.250,2042-05-15,83.67188,4.638843,0.624260,1.432526,4.28,0.744536
56,T,4.125,2044-08-15,92.93750,4.682193,0.884014,1.352729,4.28,0.848775
10,T,3.125,2043-02-15,81.25000,4.681269,0.628831,1.333961,4.28,0.746513
14,T,3.625,2044-02-15,86.71875,4.690879,0.766388,1.312932,4.28,0.802616
6,T,3.125,2042-02-15,82.52344,4.624323,0.689046,1.079454,4.28,0.823684
58,T,4.750,2045-02-15,101.17190,4.658883,1.150788,1.009911,4.28,1.032354
5,T,3.125,2041-11-15,82.84375,4.609940,0.706049,0.982610,4.28,0.853524
7,T,3.000,2042-05-15,80.70313,4.641825,0.711905,0.833144,4.28,0.869102
15,T,3.375,2044-05-15,83.37500,4.699355,0.922327,0.440880,4.28,1.000425
8,T,2.750,2042-08-15,77.35938,4.660917,0.762853,0.364714,4.28,0.944434
9,T,2.750,2042-11-15,77.00781,4.674950,0.761252,0.348710,4.28,0.945694
11,T,2.875,2043-05-15,78.00000,4.685697,0.831858,0.212125,4.28,0.991286
46,T,2.375,2042-02-15,73.43750,4.660013,0.690631,0.192954,4.28,0.935695
16,T,3.125,2044-08-15,79.92188,4.713645,0.980562,-0.055006,4.28,1.080559
43,T,2.250,2041-05-15,73.28125,4.610837,0.802691,-0.486159,4.28,1.090413
17,T,3.000,2044-11-15,78.08594,4.721617,1.069451,-0.604508,4.28,1.191798
45,T,2.000,2041-11-15,69.42188,4.656076,0.781313,-0.769216,4.28,1.094097
19,T,3.000,2045-05-15,77.67969,4.728033,1.211485,-1.192839,4.28,1.328423
42,T,1.875,2041-02-15,69.37500,4.609093,0.839424,-1.199392,4.28,1.184666
44,T,1.750,2041-08-15,66.96875,4.645671,0.859625,-1.524671,4.28,1.211395
21,T,3.000,2045-11-15,77.35938,4.727280,1.416129,-2.044363,4.28,1.528801
20,T,2.875,2045-08-15,75.89844,4.727025,1.378396,-2.065481,4.28,1.501955
18,T,2.500,2045-02-15,71.39844,4.731749,1.299669,-2.363590,4.28,1.479014
41,T,1.375,2040-11-15,64.16406,4.609714,0.924680,-2.509291,4.28,1.358580
26,T,3.000,2047-02-15,76.30469,4.750595,1.609661,-2.863555,4.28,1.700062
25,T,2.875,2046-11-15,74.80469,4.748394,1.614527,-3.127455,4.28,1.731408
27,T,3.000,2047-05-15,76.11719,4.753605,1.667139,-3.132877,4.28,1.763271
40,T,1.125,2040-08-15,61.89844,4.599389,0.980520,-3.280442,4.28,1.457618
33,T,3.375,2048-11-15,80.45313,4.759649,1.931774,-3.557241,4.28,1.970966
31,T,3.125,2048-05-15,77.14063,4.764131,1.827323,-3.596018,4.28,1.898857
22,T,2.500,2046-02-15,70.44531,4.741657,1.583096,-3.685811,4.28,1.749749
30,T,3.000,2048-02-15,75.56250,4.762594,1.812387,-3.751799,4.28,1.892905
23,T,2.500,2046-05-15,70.17188,4.748120,1.612972,-3.853672,4.28,1.782841
28,T,2.750,2047-08-15,72.43750,4.762701,1.755448,-4.004428,4.28,1.871491
29,T,2.750,2047-11-15,72.24219,4.764870,1.816782,-4.304777,4.28,1.937767
32,T,3.000,2048-08-15,75.25781,4.763645,1.950991,-4.357437,4.28,2.027452
24,T,2.250,2046-08-15,66.54688,4.755798,1.732640,-4.995709,4.28,1.924519
34,T,3.000,2049-02-15,74.97656,4.763262,2.113035,-5.066671,4.28,2.185751
35,T,2.875,2049-05-15,73.06250,4.762440,2.252126,-5.994386,4.28,2.345809
37,T,2.375,2049-11-15,65.56250,4.761726,2.579764,-9.032510,4.28,2.726481
36,T,2.250,2049-08-15,63.89844,4.766794,2.513895,-9.123486,4.28,2.670509
38,T,2.000,2050-02-15,59.96875,4.758819,2.807163,-11.704763,4.28,2.988588
39,T,1.250,2050-05-15,49.08594,4.730945,3.403333,-19.714068,4.28,3.674685

In [86]:
WNM5.OADLV(tradeDate = '2025-03-07', actualRepo = 4.380, repo_model = 'const_carry')

In [87]:
ctd_data = WNM5.ctd_data

In [88]:
bond_sim = WNM5.bond_sim

In [89]:
ctd_data = ctd_data[['shock', 'ticker', 'coupon', 'maturity', 'theo_futures_px', 'implied_repo', 'opt_free_futures_px', 'switch_option']].set_index('shock')

In [91]:
ctd_data[(ctd_data.index % 5 == 0) & (ctd_data.index >= -250) & (ctd_data.index <= 250)].to_excel('test.xlsx')

In [44]:
ctd_data.to_excel('ctd_data_2.xlsx')

In [78]:
WNM5.adj_vol

59.12844622920236

In [105]:
(WNM5.last_delivery - WNM5.tradeDate).astype(int) / 365

0.3150684931506849

In [31]:
# def switch_option(ctd_data, ctd_distr_rng = 400):
ctd_distr_rng = 400

# Set the number of shocks, such that the scenarios are a symmetric set of points around the current market level.
k_shocks = int(ctd_distr_rng + 1)

# Set the distribution range to price the switch option over
distr_shocks = np.linspace(-ctd_distr_rng / 2, ctd_distr_rng / 2, k_shocks)
nvol = WNM5.nvol
expT = (WNM5.last_delivery - WNM5.tradeDate).astype(int) / 365
z_scores = distr_shocks / (nvol * expT)

In [32]:
bond_sim = WNM5.bond_sim

In [36]:
import numpy as np
from scipy.stats import norm

cum_prob = norm.cdf(z_scores)
diff_prob = np.diff(cum_prob, prepend=0)

# import XBond as xb

# xbond_data = bond_data.drop_duplicates(subset = 'isin')
# # Set the simulation range for the cheapest-to-deliver analysis
# simulation_range = 800

# # Set the number of shocks, such that the scenarios are a symmetric set of points around the current market level.
# n_shocks = int(simulation_range + 1)

# # Generate the shocks as a vector.
# shocks = np.linspace(-simulation_range / 2, simulation_range / 2, n_shocks)


# bond_shock_matrix = xb.bond_price_shock(trade = trade_date,
#                                         settle = settle_date,
#                                         maturity = xbond_data["maturity"].values.astype("datetime64[D]"),
#                                         coupon = xbond_data["coupon"].values,
#                                         rfr_curve = sofr_curve,
#                                         clean_px = xbond_data["price"].values,
#                                         z = xbond_data['z_spread'].values,
#                                         par_shock = shocks)

ctd_set = tuple(ctd_data['isin'].drop_duplicates().to_list())
opt_free_ctd_fut_px = bond_sim[bond_sim['isin'].isin(ctd_set)].pivot(index = 'shock', columns = 'isin', values = 'opt_free_futures_px').reset_index()
ctd_theo_cols = [x + '_theo' for x in ctd_set]
ctd_data[ctd_theo_cols] = opt_free_ctd_fut_px[list(ctd_set)]
ctd_theo_sim_cols = [x + '_theo_sim' for x in ctd_set]
ctd_data[ctd_theo_sim_cols] = ctd_data[ctd_theo_cols].rolling(window=k_shocks, center = True).apply(lambda x :  np.dot(x, diff_prob), raw=True)
ctd_data['sim_theo'] = ctd_data['opt_free_futures_px'].rolling(window=k_shocks, center = True).apply(lambda x : np.dot(x, diff_prob), raw=True)
ctd_data['sim_ctd_price'] = ctd_data.apply(lambda row : row[row['isin'] + '_theo_sim'], axis = 1)
ctd_data['switch_option'] = ctd_data['sim_ctd_price'] - ctd_data['sim_theo']

In [43]:
ctd_data.to_excel('ctd_data_wth_switch_option.xlsx')

In [120]:
ctd_data = ctd_data[(ctd_data['shock'] > -151) & (ctd_data['shock'] < -140)]
ctd_data['opt_free_delivery_px'] = ctd_data['opt_free_futures_px'] * ctd_data['Conversion Factor']

In [121]:
import numpy as np
import XBond as xb

In [122]:
# Need to extend to case with two or more coupons
def _irr(bond_data, delivery_time):

    # Set the relevant data fields to arrays
    settle = bond_data['settle_date'].values.astype('datetime64[D]')
    delivery = bond_data[delivery_time].values.astype('datetime64[D]')
    coupon = bond_data['coupon'].values
    freq = bond_data['freq'].values
    maturity = bond_data['maturity'].values.astype('datetime64[D]')
    price = bond_data['price'].values
    delivery_price = bond_data['delivery_price'].values
    ncd = bond_data['NCD'].values.astype('datetime64[D]')

    # C to be the value of the first coupon paid in the intervening period between the futures settlement date and the delivery date
    c = np.where(delivery < ncd, 0, coupon)

    # Dirty price of the bonds
    dirty_price = price + xb.acc_int(settle = settle, maturity = maturity, coupon = coupon, cpn_freq = freq)
    print(dirty_price)
    
    # Dirty invoice prices
    dirty_delivery_price = delivery_price + xb.acc_int(settle = delivery, maturity = maturity, coupon = coupon, cpn_freq = freq)
    print(dirty_delivery_price)

    # Days between futures settlement and delivery
    n = (delivery - settle).astype(int)
    print(n)

    # Days between the next coupon date and delivery
    n2 = (delivery - ncd).astype(int)
    print(n2)

    # Return the implied repo rate, MWRR on the principal and coupon accrued at repo rate on ACT/360 or ACT/365 day count
    return ((dirty_delivery_price + c / freq - dirty_price) * 360) / (dirty_price * n - c / freq * n2) * 100

In [123]:
ctd_data['irr'] = _irr(ctd_data, delivery_time = 'last_delivery')

[133.89700572 133.66675131 133.43703849 133.20786586 132.97923199
 132.75113547 132.52357489 132.29654884 132.07005592 131.84409473]
[132.76659106 132.53849563 132.31093194 132.08389861 131.85739426
 131.63141751 131.405967   131.18104136 130.95663921 130.73275922]
[117 117 117 117 117 117 117 117 117 117]
[46 46 46 46 46 46 46 46 46 46]

In [124]:
ctd_data['irr']

250    2.880114
251    2.890115
252    2.900116
253    2.910117
254    2.920118
255    2.930119
256    2.940120
257    2.950121
258    2.960122
259    2.970123
Name: irr, dtype: float64